const { APP_NAME, MAINTENANCE_MESSAGE, SERVER_ID, WELCOME_CHANNEL_ID, MAINTENANCE_CHANNEL_ID } = require('./config');

module.exports = {
  APP_NAME,
  MAINTENANCE_MESSAGE,
  SERVER_ID,
  WELCOME_CHANNEL_ID,
  MAINTENANCE_CHANNEL_ID
};
